version: 2

models:
  - name: stg_ecommerce_data
    description: "A staging model that cleans and prepares the raw e-commerce data for analysis."
    columns:
      - name: TransactionID
        description: "Unique identifier for each transaction."
        tests:
          - not_null
          - unique

      - name: order_date
        description: "The date when the transaction occurred."

      - name: CustomerID
        description: "Unique identifier for the customer."
        tests:
          - not_null

      - name: CustomerName
        description: "Name of the customer."

      - name: CustomerCity
        description: "City where the customer resides."

      - name: CustomerCountry
        description: "Country where the customer resides."

      - name: ProductID
        description: "Unique identifier for the product."
        tests:
          - not_null

      - name: ProductName
        description: "Name of the product."

      - name: ProductCategory
        description: "Category to which the product belongs."

      - name: ProductSubcategory
        description: "Subcategory under the main product category."

      - name: UnitPrice
        description: "Price per unit of the product."
        tests:
          - not_null

      - name: Quantity
        description: "Number of units of the product purchased."
        tests:
          - not_null

      - name: TotalAmount
        description: "Total amount for the transaction, calculated as UnitPrice * Quantity."
        tests:
          - not_null

models:
  - name: dim_customer
    description: "A staging model that cleans and prepares the raw e-commerce data for analysis."
    columns:
      - name: CustomerID
        description: "Unique identifier for each transaction."
        tests:
          - not_null
          - unique

models:
  - name: dim_product
    description: "A staging model that cleans and prepares the raw e-commerce data for analysis."
    columns:
      - name: ProductID
        description: "Unique identifier for each transaction."
        tests:
          - not_null
          - unique


models:
  - name: fct_sales
    description: "A staging model that cleans and prepares the raw e-commerce data for analysis."
    columns:
      - name: TransactionID
        description: "Unique identifier for each transaction."
        tests:
          - not_null
          - unique
      - name: CustomerID
        description: "Unique identifier for each transaction."
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: CustomerID
      - name: ProductID
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: ProductID
