sources:
  - name: raw
    description: "Source data from the raw e-commerce dataset."
    database: ecommerce
    schema: raw
    tables:
      - name: ECOMMERCE_DATA
        description: "Raw e-commerce data loaded from the CSV file."
